plugins:
  - uses:
    - plugin: Meniole/plugin-template@fix/updates
    # - plugin: https://comic-bee-miserably.ngrok-free.app
  - uses:
    - plugin: https://your-plugin-name-development.fernand-veyrier.workers.dev
  - uses:
      - plugin: Meniole/text-conversation-rewards@development
      # - plugin: https://comic-bee-miserably.ngrok-free.app
        with:
          logLevel: "debug"
          evmNetworkId: 100
          evmPrivateEncrypted: "giLxu7IVSTpEFO89DaeCgnkKemYf2aFlK9EUQkbt71YmFOcQdIkCT8JDpX5zV5Sg1TqBeziZ486U0E3a6nD3emg0x9oeG3ILRUTlOE4I3RBZ0yTadsnV4RvewJMCMZJaYDuom-rHzog8p9InBwaHBszFeWItttSwS7o" # https://github.com/ubiquibot/conversation-rewards/pull/111#issuecomment-2348639931
          erc20RewardToken: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"
          incentives:
            allowContributorGeneration: false
            limitRewards: true
            requirePriceLabel: true
            # contentEvaluator:
            #   openAi:
            #     endpoint: "http://localhost:4000/openai"
            #   multipliers:
            #     - role:
            #         - "ISSUE_SPECIFICATION"
            #       relevance: 1
            userExtractor:
              redeemTask: true
            dataPurge:
              skipCommentsWhileAssigned: "none"
            reviewIncentivizer:
              baseRate: 100
              conclusiveReviewCredit: 25
            formattingEvaluator:
              multipliers:
                - role:
                    - ISSUE_SPECIFICATION
                  multiplier: 3
                  rewards:
                    wordValue: 0.1
                    html:
                      br:
                        score: 0
                        countWords: true
                      code:
                        score: 5
                        countWords: false
                      p:
                        score: 0
                        countWords: true
                      em:
                        score: 0
                        countWords: true
                      img:
                        score: 5
                        countWords: true
                      strong:
                        score: 0
                        countWords: false
                      blockquote:
                        score: 0
                        countWords: false
                      h1:
                        score: 1
                        countWords: true
                      h2:
                        score: 1
                        countWords: true
                      h3:
                        score: 1
                        countWords: true
                      h4:
                        score: 1
                        countWords: true
                      h5:
                        score: 1
                        countWords: true
                      h6:
                        score: 1
                        countWords: true
                      a:
                        score: 5
                        countWords: true
                      li:
                        score: 0.5
                        countWords: true
                      ul:
                        score: 0
                        countWords: true
                      td:
                        score: 0
                        countWords: true
                      hr:
                        score: 0
                        countWords: true
                      pre:
                        score: 0
                        countWords: false
                      ol:
                        score: 0
                        countWords: true
                - role:
                    - ISSUE_AUTHOR
                    - ISSUE_COLLABORATOR
                    - PULL_COLLABORATOR
                  multiplier: 1
                  rewards:
                    wordValue: 0.1
                    html:
                      br:
                        score: 0
                        countWords: true
                      code:
                        score: 5
                        countWords: false
                      p:
                        score: 0
                        countWords: true
                      em:
                        score: 0
                        countWords: true
                      img:
                        score: 5
                        countWords: true
                      strong:
                        score: 0
                        countWords: false
                      blockquote:
                        score: 0
                        countWords: false
                      h1:
                        score: 1
                        countWords: true
                      h2:
                        score: 1
                        countWords: true
                      h3:
                        score: 1
                        countWords: true
                      h4:
                        score: 1
                        countWords: true
                      h5:
                        score: 1
                        countWords: true
                      h6:
                        score: 1
                        countWords: true
                      a:
                        score: 5
                        countWords: true
                      li:
                        score: 0.5
                        countWords: true
                      ul:
                        score: 0
                        countWords: true
                      td:
                        score: 0
                        countWords: true
                      hr:
                        score: 0
                        countWords: true
                      pre:
                        score: 0
                        countWords: false
                      ol:
                        score: 0
                        countWords: true
                - role:
                    - ISSUE_CONTRIBUTOR
                    - ISSUE_ASSIGNEE
                  multiplier: 0.25
                  rewards:
                    wordValue: 0.1
                    html:
                      br:
                        score: 0
                        countWords: true
                      code:
                        score: 5
                        countWords: false
                      p:
                        score: 0
                        countWords: true
                      em:
                        score: 0
                        countWords: true
                      img:
                        score: 5
                        countWords: true
                      strong:
                        score: 0
                        countWords: false
                      blockquote:
                        score: 0
                        countWords: false
                      h1:
                        score: 1
                        countWords: true
                      h2:
                        score: 1
                        countWords: true
                      h3:
                        score: 1
                        countWords: true
                      h4:
                        score: 1
                        countWords: true
                      h5:
                        score: 1
                        countWords: true
                      h6:
                        score: 1
                        countWords: true
                      a:
                        score: 5
                        countWords: true
                      li:
                        score: 0.5
                        countWords: true
                      ul:
                        score: 0
                        countWords: true
                      td:
                        score: 0
                        countWords: true
                      hr:
                        score: 0
                        countWords: true
                      pre:
                        score: 0
                        countWords: false
                      ol:
                        score: 0
                        countWords: true
                - role:
                    - PULL_SPECIFICATION
                    - PULL_AUTHOR
                    - PULL_ASSIGNEE
                    - PULL_CONTRIBUTOR
                  multiplier: 0
                  rewards:
                    wordValue: 0
                    html:
                      br:
                        score: 0
                        countWords: true
                      code:
                        score: 5
                        countWords: false
                      p:
                        score: 0
                        countWords: true
                      em:
                        score: 0
                        countWords: true
                      img:
                        score: 5
                        countWords: true
                      strong:
                        score: 0
                        countWords: false
                      blockquote:
                        score: 0
                        countWords: false
                      h1:
                        score: 1
                        countWords: true
                      h2:
                        score: 1
                        countWords: true
                      h3:
                        score: 1
                        countWords: true
                      h4:
                        score: 1
                        countWords: true
                      h5:
                        score: 1
                        countWords: true
                      h6:
                        score: 1
                        countWords: true
                      a:
                        score: 5
                        countWords: true
                      li:
                        score: 0.5
                        countWords: true
                      ul:
                        score: 0
                        countWords: true
                      td:
                        score: 0
                        countWords: true
                      hr:
                        score: 0
                        countWords: true
                      pre:
                        score: 0
                        countWords: false
                      ol:
                        score: 0
                        countWords: true
              wordCountExponent: 0.85
            # permitGeneration: {}
            githubComment:
              post: true
              debug: false
          dataCollection:
            maxAttempts: 10
            delayMs: 1000
  - uses:
      - plugin: Meniole/ubiquity-os-kernel-telegram@development
        with:
          botId: 7543249164
  - uses:
      - plugin: https://ubiquity-os-telegram-bridge-development.fernand-veyrier.workers.dev
        with:
          botId: 7543249164
  - uses:
    - plugin: Meniole/command-ask@development
      with:
        model: "openai/o1-mini"
        openAiBaseUrl: "https://openrouter.ai/api/v1"
  - skipBotEvents: false
    uses:
      - plugin: https://ubiquity-os-command-start-stop-development.fernand-veyrier.workers.dev
      # - plugin: https://comic-bee-miserably.ngrok-free.app
        with:
          reviewDelayTolerance: "3 Days"
          taskStaleTimeoutDuration: "30 Days"
          startRequiresWallet: false
          maxConcurrentTasks:
            member: 2
            contributor: 2
          emptyWalletText: "Please set your wallet address with the /wallet command first and try again."
          rolesWithReviewAuthority:
            - "COLLABORATOR"
            - "OWNER"
            - "MEMBER"
            - "ADMIN"
          requiredLabelsToStart:
            - name: "Priority: 1 (Normal)"
              allowedRoles: ['collaborator']                
            - name: "Priority: 2 (Medium)"
              allowedRoles: ['contributor']            
            - name: "Priority: 3 (High)"
              allowedRoles: ['collaborator', 'contributor']
            - name: "Priority: 4 (Urgent)"
              allowedRoles: ['collaborator']
            - name: "Priority: 5 (Emergency)"

  # - uses:
  #     - plugin: https://ubiquity-os-comment-vector-embeddings-development.fernand-veyrier.workers.dev
  #       with:
  #         matchThreshold: 0.95
  #         warningThreshold: 0.75
  #         jobMatchingThreshold: 0.75
  - uses:
      - plugin: https://ubiquity-os-command-wallet-development.fernand-veyrier.workers.dev
      # - plugin: https://comic-bee-miserably.ngrok-free.app
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquity-os-command-query-user-development.fernand-veyrier.workers.dev
      # - plugin: https://comic-bee-miserably.ngrok-free.app
        with:
          allowPublicQuery: true
  - uses:
      # - plugin: Meniole/daemon-pricing@development
      # - plugin: Meniole/daemon-pricing@fix/action-base-rate
      - plugin: https://ubiquity-os-daemon-pricing-development.fernand-veyrier.workers.dev
      # - plugin: https://comic-bee-miserably.ngrok-free.app
        with:
          labels:
            time:
              - name: "Time: <1 Hour"
                collaboratorOnly: false
              - name: "Time: <2 Hours"
                collaboratorOnly: false
              - name: "Time: <4 Hours"
                collaboratorOnly: false
              - name: "Time: <1 Day"
                collaboratorOnly: false
              - name: "Time: <1 Week"
                collaboratorOnly: false
            priority:
              - name: "Priority: 0 (Regression)"
                collaboratorOnly: false 
              - name: "Priority: 1 (Normal)"
                collaboratorOnly: false
              - name: "Priority: 2 (Medium)"
                collaboratorOnly: false
              - name: "Priority: 3 (High)"
                collaboratorOnly: false
              - name: "Priority: 4 (Urgent)"
                collaboratorOnly: false
              - name: "Priority: 5 (Emergency)"
                collaboratorOnly: false
          basePriceMultiplier: 1.75
          publicAccessControl:
            setLabel: false
            fundExternalClosedIssue: false
  - uses:
      - plugin: Meniole/daemon-disqualifier@development
      # - plugin: https://comic-bee-miserably.ngrok-free.app
        with:
          warning: "1 minute"
          pullRequestRequired: true
          eventWhitelist:
            - 'pull_request.review_requested'
            - 'pull_request.ready_for_review'
            - 'pull_request_review_comment.created'
            - 'issue_comment.created'
            - 'push'
          watch:
            optOut:
              - ubiquibot
              - launch-party
              - staging
              - production
          disqualification: "2 minutes"
  - uses:
      - plugin: Meniole/daemon-merging@development
      # - plugin: https://comic-bee-miserably.ngrok-free.app
        with:
          approvalsRequired:
            collaborator: 1
            contributor: 2
          mergeTimeout:
            collaborator: "3.5 days"
            contributor: "7 days"
          repos:
            monitor: []
            ignore:
              - ubiquibot
              - launch-party
              - staging
              - production
          allowedReviewerRoles:
            - "COLLABORATOR"
            - "MEMBER"
            - "OWNER"
  - uses:
      - plugin: Meniole/text-vector-embeddings@development
        with:
          matchThreshold: 0.90
          warningThreshold: 0.70
          jobMatchingThreshold: 0.75

  - uses:
      - plugin: Meniole/daemon-pull-review@development
      # - plugin: https://comic-bee-miserably.ngrok-free.app
        with:
          openRouterBaseUrl: "https://api.openai.com/v1"
          openRouterAiModel: "gpt-4o"
